blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('myblog.urls')),  # 所有blog/urls.py里的路由都有前缀'blog/'
    url(r'', include('comments.urls')),
    url(r'^accounts/', include('users.urls')),
    #将 auth 应用中的urls模块包含进来
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

comments/urls.py
from django.conf.urls import url
from .import views

app_name = 'comment'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),


]

myblog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
app_name  = 'myblog'

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name= 'index'),
    #url(r'detail/$',views.detail,name = 'datail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    #限制访问的路由,当点击某一篇文章的时候，要展示文章详情页的时候！！！如果没有登陆，
    #限制访问，所以限制的是访问某一篇文章时候的视图函数
    #url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$',login_required(views.PostDetailView.as_view()),name='detail'
),

]
'''
而当用户访问 <网站域名>/post/2/ 时，显示的是第二篇文章的内容，这里数字代表了第几篇文
章，也就是数据库中 Post 记录的 id 值。
被括起来的部分 (?P<pk>[0-9]+)匹配 255，
那么这个 255 会在调用视图函数 detail 时被传递进去给到参数 pk，实际上视图函数
的调用就是这个样子：detail(request, pk=255)。我们这里必须从 URL 里捕获文章的
id，因为只有这样我们才能知道用户访问的究竟是哪篇文章。

'''

users/urls.py
from django.conf.urls import url
from .import views

app_name = 'users'

urlpatterns = [
    url(r'register/$',views.register,name='register'),
    #url(r'login/$',views.login,name='login'),



]

comments/models.py
from django.db import models

# Create your models here.
'''
用户评论的数据必须被存储到数据库里，以便其他用户访问时 Django 能从数据库取
回这些数据然后展示给访问的用户，因此我们需要为评论设计数据库模型，这和设计
文章、分类、标签的数据库模型是一样的。
'''
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey("myblog.Post")

    def __str__(self):
        return self.text[:30]

'''
设计数据库字段，和HTML页面 中的前段代码要相互对应

然后根据表单的要求填写相应的数据。之后用户点击评论按钮，
这些数据就会发送给某个 URL。
'''

myblog/models.py
from django.core.urlresolvers import reverse
from django.db import models

from django.contrib.auth.models import User
#from django.urls import reverse
#from django.contrib import *


#from users.models import User
#文章（Post）、分类（Category）以及标签（Tag）
# 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对
#多的关联关系，和 Category 类似。author = models.ForeignKey(User)
from django.shortcuts import redirect


class Category(models.Model):
    name = models.CharField(max_length=64)

class Tag(models.Model):
    name = models.CharField(max_length=64)

class Post(models.Model):
    title = models.CharField(max_length=64)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=256,blank=True)
# created_time、modified_time。这两个列分别表示文章的创建时间和最后一次修
# 改时间，存储时间的列用DateTimeField数据类型
#关系-----------
# 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag,blank=True)
    author = models.ForeignKey(User)

    views =models.PositiveIntegerField(default=0)
#这里我们通过 ForeignKey 把文章和 User 关联了起来，
#因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是
#一对多的关联关系，和 Category 类似.

    def get_absolute_url(self):
        return reverse('myblog:detail',kwargs={"pk":self.pk})
#这个方法到底是怎么写出来的呢   还有 pk = id ???
# 在 urls.py 中加上了app_name = 'myblog',,,所以这里也要加上‘myblog’

    def increase_views(self):
        self.views +=1
        self.save(update_fields=['views'])
'''
  increase_views 方法首先将自身对应的 views 字段
的值 +1（此时数据库中的值还没变），然后调用 save 
方法将更改后的值保存到数据库。注意这里使用了 update_fields 
参数来告诉 Django 只更新数据库中 views 字段的值，以提高

'''

'''
context_object_name————在模板中的变量名。{{name}}
template_name————-模板一般是一个html文件名
paginate_by————如果做分页这个参数说明每页有几个item项
model——————对应的模型（Model）
http_method_names———-请求类型 可以是get或者post

'''











'''
超级用户：963.
密码：963.8520

'''

myblog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from  .models import  Post,Category
from comments.forms import CommentForm

'''
def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request,'myblog/index.html',context={"post_list":post_list})
这代码的作用：连接数据库 和 HTML页面展示页
Post.objects.all() 这个方法从数据库中去出来，所有的存在数据库中的文章
在admin后台中 post中写文章，保存以后就直接存到了数据库中
'''
#    model：将 model 指定为 Post，告诉 Django 我要获取的模型是 Post。
# • template_name：指定这个视图渲染的模板。
# • context_object_name：指定获取的模型列表数据保存的变量名。这个变量会被
# 传递给模板。
from django.views.generic import ListView
class IndexView(ListView):
    model = Post
    template_name = 'myblog/index.html'
    context_object_name = 'post_list'



'''
def detail(request, pk):
    post = get_object_or_404(Post,pk=pk)
    post.increase_views()
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post':post,
               'form':form,
               'comment_list':comment_list}
    return render(request, 'myblog/detail.html', context=context)

   视图函数很简单，它根据我们从 URL 捕获的文章 id（也就是 pk，这里 pk 和 id 是等
价的）获取数据库中文章 id 为该值的记录，然后传递给模板。注意这里我们用到了从
django.shortcuts 模块导入的 get_object_or_404 方法，其作用就是当传入的 pk 对应的
Post 在数据库存在时，就返回对应的 post，如果不存在，就给用户返回一个 404 错
误，表明用户请求的文章不存在。

------------------------------------------------------------------------------
    紧接着我们覆写了 get 方法。这对应着 detail 视图函数中将 post 的阅读量 +1 的
那部分代码。事实上，你可以简单地把 get 方法的调用看成是 detail 视图函数的调
用。
    接着我们又复写了 get_object 方法。这对应着 detail 视图函数中根据文章的 id（也
就是 pk）获取文章，然后对文章的 post.body 进行 Markdown 渲染的代码部
分。
    最后我们复写了 get_context_data 方法。这部分对应着 detail 视图函数中生成评论表
单、获取 post 下的评论列表的代码部分。这个方法返回的值是一个字典，这个字
典就是模板变量字典，最终会被传递给模板。
    你也许会被这么多方法搞乱，为了便于理解，你可以简单地把 get 方法看成
是 detail 视图函数，至于其它的像 get_object、get_context_data 都是辅助方法，这
些方法最终在 get 方法中被调用，这里你没有看到被调用的原因是它们隐含在
了 super(PostDetailView, self).get(request, *args, **kwargs) 即父类 get 方法的调用中。
    最终传递给浏览器的 HTTP 响应就是 get 方法返回的 HttpResponse 对象。
这些方法的相同点：都执行了父类方法，然后对父类方法的返回值进行一些操作，
最后返回这个修改后的返回值。
'''
# 此外我们可以看到 CategoryView 类中指定的属性值和 IndexView 中是一模一样的，
# 所以如果为了进一步节省代码，甚至可以直接继承 IndexView：
from django.views.generic import DetailView
class PostDetailView(DetailView):
    model = Post
    template_name = 'myblog/detail.html'
    context_object_name = 'post'
    def get(self,request,*args,**kwargs):
        response =super(PostDetailView,self).get(request,*args,**kwargs)
        self.object.increase_views()
        return response
    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        return post
    def get_context_data(self, **kwargs):
        context = super(PostDetailView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context
'''
def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month ).order_by('-created_time')
    return render(request, 'myblog/index.html', context={'post_list': post_list})
'''
class ArchivesView(IndexView):
    def get_queryset(self):
        return super(ArchivesView,self).get_queryset().filter(
            created_time__year = self.kwargs.get('year'),
            created_time__month = self.kwargs.get('month')
        )




'''
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'myblog/index.html', context={'post_list': post_list})

这里我们首先根据传入的 pk 值（也就是被访问的分类的 id 值）从数据库中获取到这
个分类。get_object_or_404 函数和 detail 视图中一样，其作用是如果用户访问的分类不
存在，则返回一个 404 错误页面以提示用户访问的资源不存在。然后我们通
过 filter 函数过滤出了该分类下的全部文章。同样也和首页视图中一样对返回的文章列
表进行了排序。

显示在主页中， 因为只有当现实一篇文章的时候，才用到 detail 模板；
'''
class CategoryView(IndexView):
    model = Post
    template_name = 'myblog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category = cate)

templates/myblog/base.html
{% load staticfiles %}
{% load myblog_tags %}


<html>
<head>
    <meta charset="UTF-8">
    <title>
        {{title}}
    </title>

    <link rel="stylesheet" href="{% static 'myblog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/pace.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <script src="{% static 'myblog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'myblog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/pace.min.js' %}"></script>
    <script src="{% static 'myblog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'myblog:index' %}"><b>渣渣的</b> &amp;博客</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bsexample-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'myblog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="fullwidth.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                            {% if user.is_authenticated %}
                            <li class="cl-effect-11"><a href="{% url 'logout' %}" data-hover="注销">注销</a></li>
                            <li class="cl-effect-11"><a href="{% url 'password_change' %}">修改密码</a></li>
                            {% else %}
                            <li class="cl-effect-11"><a href="{% url 'login' %}">登陆</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="searchicon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ionios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}


                {% endblock %}
            </main>

            <aside class="col-md-4">
                {% block toc %}

                    
                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>

                    {% get_recent_post as recent_post_list %}
                    <ul>
                     {% for post in recent_post_list %}
                        <li>
                            <a href = "{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                            {% empty %}
                            没有文章！
                            {% endfor %}
                    </ul>

                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'myblog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                         暂时没有归档文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'myblog:category' category.pk %}">{{ category.name }} <span class="post-count">(13)</span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rssoutline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a></p>
            </div>
        </div>
    </div>
</footer>

<!--<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ionios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
            <li><a href="contact.html">登陆</a></li>

        </ul>
    </nav>
</div>-->

<script src="{% static 'myblog/js/script.js' %}"></script>
</body>
</html>

templates/myblog/detail.html
{% extends 'myblog/base.html' %}


{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body }}
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>


    <form action="{% url 'comment:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="i{{ form.mame.id_for_label }}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">网址：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
                 <button type="submit" class="comment-btn">发表</button>
            </div>
        </div> <!-- row -->
    </form>
    <!-- form.name  form.email form.url 等将自动渲染成表单控件-->





    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
        <ul>
            {% for comment in comment_list %}
            <li class = "comment-item">
                <span class = "nickname">{{ comment.name }}</span>
                <time class="submit-date">{{ comment.created_time }}</time>
                <div class="text">{{ comment.text }}</div>
            </li>
            {% empty %}
            暂时没有评论！
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}

templates/myblog/index.html
{% extends 'myblog/base.html' %}



{% block main %}
{% for post in post_list %}

<!-- for post in post_list 这句话一定出现在index页面，因为要对数据库中的文章进行遍历，循环拿出来里面所有的文章-->
<!--而在 detail中就没有，直接开始解析拿到的某一篇文章-->
<!--post.pk的作用是，首先拿到指定的文章，，接下来就开始，对文章进行各种的解析-->
<!--拿到不同的pk 就是拿到不同的文章-->

<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a></span>
        </div>
    </header>

    <div class="entry-content clearfix">
        <p>{{  post.body|truncatechars:100 }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>

</article>



{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}
<!-- 简单分页效果
<div class="pagination-simple">
<a href="#">上一页</a>
<span class="current">第 6 页 / 共 11 页</span>
<a href="#">下一页</a>
</div>
-->
<div class="pagination">
    <ul>
        <li><a href="">1</a></li>
        <li><a href="">...</a></li>
        <li><a href="">4</a></li>
        <li><a href="">5</a></li>
        <li class="current"><a href="">6</a></li>
        <li><a href="">7</a></li>
        <li><a href="">8</a></li>
        <li><a href="">...</a></li>
        <li><a href="">11</a></li>
    </ul>
</div>
{% endblock main %}